#include<stdio.h>
int main()
{
    int i,j,n,m,arr[100][100],r[100],s=0,z=0,max;
    scanf("%d%d",&n,&m);
    for(i=0;i<n;i++)
    {
        for(j=0;j<m;j++)
        {
            scanf("%d",&arr[i][j]);
        }
    }
    z=0;
     for(i=0;i<n;i++)
    {
        s=0;
        for(j=0;j<m;j++)
        {
            s=s+arr[i][j];
        }
        r[z++]=s;
    }
    max=r[0];
    for(i=1;i<n;i++)
    {
        if(max<r[i])
        {
            max=r[i];
        }
    }
    printf("%d",max);
}